---
downloads: ~/.ansible-downloads/

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
 - Launchpad
 - TV
 - FaceTime
 - Podcasts
 - 'App Store'
dockitems_persist:
 - name: "Authy"
   path: "/Applications/Authy Desktop.app/"
   pos: 10
 - name: "Google Chrome"
   path: "/Applications/Google Chrome.app/"
   pos: 11

homebrew_installed_packages:
  - aquasecurity/trivy/trivy
  - argocd
  - autoconf
  - aws-vault
  - azure-cli
  - bat
  - bfg
  - colordiff
  - derailed/k9s/k9s
  - diff-so-fancy
  - docker-credential-helper-ecr
  - duf
  - fzf
  - hashicorp/tap/vault
  - hashicorp/tap/packer
  - go
  - goenv
  - gnupg
  - htop
  - kubernetes-cli
  - kubeseal
  - kustomize
  - mercurial
  - openjdk
  - nvm
  - podman
  - pyenv
  - ruby
  - sops
  - telnet
  - terraform
  - terraform-docs
  - terragrunt
  - tfenv
  - tflint
  - tmux
  - tree
  - ytt


homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - hashicorp/tap
  - vmware-tanzu/carvel

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - authy
  - docker
  - font-hack-nerd-font
  - iterm2
  - google-chrome
  - joplin
  - lastpass
  - lens
  - miro
  - openvpn-connect
  - pritunl
  - slack
  - visual-studio-code
  - virtualbox
  - vlc
  - whatsapp
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# defaults file for iterm2-shell-integration
# install script
iterm2_shell_integration_script: .iterm2_shell_integration.zsh
# base url to download from
iterm2_shell_integration_download_url: https://iterm2.com/shell_integration/zsh


# Kubectl Plugins
kubectl_plugins:
- access-matrix 
- ctx
- df-pv
- doctor
- get-all
- iexec
- ingress-nginx
- node-shell
- ns
- popeye
- prompt
- rbac-lookup
- rolesum
- tail
- tree
- who-can
- whoami
