---
downloads: ~/.ansible-downloads/

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - FaceTime
  - Podcasts
  - "App Store"
dockitems_persist:
  - name: "Authy Desktop"
    path: "/Applications/Authy Desktop.app/"
    pos: 10
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 11

homebrew_installed_packages:
  - aquasecurity/trivy/trivy
  - ansible-lint
  - argocd
  - autoconf
  - aws-vault
  - awscli
  - azure-cli
  - bat
  - bfg
  - colordiff
  - composer
  - derailed/k9s/k9s
  - diff-so-fancy
  - docker-credential-helper-ecr
  - duf
  - elixir
  - fzf
  - hadolint
  - hashicorp/tap/vault
  - hashicorp/tap/packer
  - helm
  - gh
  - go
  - goenv
  - gnu-tar
  - gnupg
  - htop
  - name: libpq
    state: linked
  - jq
  - kind
  - kubernetes-cli
  - kubeseal
  - kustomize
  - mercurial
  - name: mysql-client
    state: linked
  - nvm
  - openjdk
  - podman
  - pre-commit
  - pyenv
  - ruby
  - shellcheck
  - shfmt
  - sops
  - telnet
  - name: terraform
    state: absent
  - terraform-docs
  - name: terragrunt
    install_options: ignore-dependencies # terraform is managed by tfenv
  - tfenv
  - tflint
  - tmux
  - tree
  - ytt

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - hashicorp/tap
  - vmware-tanzu/carvel

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - authy
  - docker
  - iterm2
  - google-chrome
  - joplin
  - lastpass
  - lens
  - macvim
  - miro
  - openvpn-connect
  - pritunl
  - slack
  - visual-studio-code
  - virtualbox
  - vlc
  - whatsapp
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A

npm_packages:
  - cspell

pip_packages:
  - virtualenvwrapper
  - yamlfix

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# iterm2-shell config
iterm2_normal_font: "Monaco 12"
iterm2_non_ascii_font: "MesloLGS-NF-Regular 12"

# Kubectl Plugins
kubectl_plugins:
  - access-matrix
  - ctx
  - df-pv
  - doctor
  - get-all
  - iexec
  - ingress-nginx
  - node-shell
  - ns
  - popeye
  - prompt
  - rbac-lookup
  - rolesum
  - tail
  - tree
  - who-can
  - whoami

# Fonts must point to a repository/archived repo with a directory containing .ttf or .otf files
fonts:
  - name: Monaco
    repo: https://github.com/Karmenzind/monaco-nerd-fonts.git
    dirs: ["fonts",]
  - name: Meslo
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip
    dirs: ["."]
  - name: FiraCode
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
    dirs: ["."]
  - name: UbuntuMono
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/UbuntuMono.zip
    dirs: ["."]

zsh_plugins:
  - name: zsh-autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
  - name: zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git

required_directories:
  - "{{ ansible_env.HOME }}/.nvm"
  - "{{ ansible_env.HOME }}/.terraform.d/cache"


git_configs:
  - name: core.excludesfile
    value: "{{ ansible_env.HOME }}/.gitignore"
