---
- name: Create /tmp/{{ item.name }} directory if not exist
  file:
    path: "/tmp/{{ item.name }}"
    state: directory
  tags: ["fonts"]

- name: Download {{ item.name }} Fonts (git repo)
  git:
    repo: "{{ item.repo }}"
    dest: "/tmp/{{ item.name }}"
    accept_hostkey: "true"
    depth: 1
  when: item.repo|default ("") != ""
  tags: ["fonts"]

- name: Download {{ item.name }} Fonts (archive URL)
  unarchive:
    src: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}"
    remote_src: yes
    creates: /tmp/{{ item.name }}/{{ item.dirs }}
  when: item.url|default ("") != ""
  tags: ["fonts"]

- name: debug
  debug:
    var: item
  tags: ["fonts"]

- name: set fact
  set_fact:
    font_dirs: "{{ font_dirs | default([]) + ['/tmp/' ~ item.name ~ '/' ~ each.0 ~'/*.'~ each.1] }}"
  loop: "{{  item.dirs | product(['ttf', 'otf'])  }}"
  loop_control:
    loop_var: each
  tags: ["fonts"]

- name: Install {{ font_name }} Font
  copy:
    src: "{{ item }}/"
    dest: "{{ fonts_dir }}"
  with_fileglob: "{{ font_dirs }}"
  tags: ["fonts"]

